(feat)ml: add model pipeline
alfcan/CADOCS_NLU_Model pull request #10
Opened 2023-06-13 20:56 UTC by alfcan

2023-06-14 18:28 UTC, davide-lagamba requested changes
In "CADOCS_NLU.ipynb", the calculation of Accuracy, Precision and Recall could be reconsidered since the values obtained are equal between them.
Some comments should be in English instead of Italian.
Some comments partially describe the code and could be changed.

2023-06-28 15:10 UTC, alfcan commented
The value of the metrics is the same since the increased dataset was used and improved performance, but the metrics are calculated differently from the previous version.

2023-06-28 15:11 UTC, alfcan commented
In this branch is also solved issue #2

2023-06-28 15:32 UTC, davide-lagamba approved these changes

2023-06-28 15:33 UTC, merged